#!/usr/bin/env sh

yabai -m config external_bar               all:0:0      \
                focus_follows_mouse        autofocus    \
                mouse_follows_focus        on           \
                window_zoom_persist        off          \
                window_placement           second_child \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                top_padding                8            \
                bottom_padding             8            \
                left_padding               8            \
                right_padding              8            \
                window_gap                 4            \
                layout                     bsp

yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off