#!/usr/bin/env sh

yabai -m config external_bar               all:42:0     \
                focus_follows_mouse        autofocus    \
                mouse_follows_focus        on           \
                window_zoom_persist        off          \
                window_placement           second_child \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                top_padding                10           \
                bottom_padding             10           \
                left_padding               10           \
                right_padding              10           \
                window_gap                 10           \
                layout                     bsp

yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add app="^System Settings$" manage=off