dev:
  packages:
    - "luarocks"
    - "nvm"
    - "go"
    - "github-cli"
    - "hub"
    - "kitty"
    - "ghostty"
    - "neovim"
    - "helix"
    - "tmux"
    - "lazygit"
    - "bruno-bin"
    # - "docker"
    # - "docker-compose"
    # - "nvidia-container-toolkit"
    - "ollama-cuda"
    - "oterm"
    - "mockoon-bin"
    - 'visual-studio-code-bin'
