dev:
  packages:
    - "nvm"
    - "go"
    - "github-cli"
    - "kitty"
    - "neovim"
    - "tmux"
    - "lazygit"
    - "bruno"
    # - "docker"
    # - "docker-compose"
    # - "nvidia-container-toolkit"
    # - "ollama-cuda"
