dev:
  packages:
    - "luarocks"
    - "fnm"
    - "go"
    - "github-cli"
    - "hub"
    - "kitty"
    - "tree-sitter-cli-git"
    - "neovim-nightly-bin"
    - "helix"
    - "tmux"
    - "lazygit"
    - "bruno-bin"
    - "docker"
    - "docker-compose"
    - "nvidia-container-toolkit"
    - "mockoon-bin"
    - "visual-studio-code-bin"
    - "opencode-bin"
