environment:
  packages:
    # Portals
    - "xdg-desktop-portal-gtk"
    - "xdg-desktop-portal-gnome"
    - "gnome-keyring"

    # Window Manager
    - "niri-git"

    - "xwayland-satellite-git"
    - "cpio"
    - "cmake"
    - "sddm"
    - "libnotify"
    - "swaync"
    - "syshud"
    # - "pamixer"
    - "polkit-gnome"
    - "qt5-wayland"
    - "qt6-wayland"
    - "python-gobject"
    - "waybar"
    - "swww"
    - "fuzzel"
    - "cliphist"
    - "nautilus"
    - "gvfs" # Dependency for thunar
    - "thunar"
    - "ffmpegthumbnailer"
    - "p7zip"
    - "poppler"
    - "yazi"
    - "eog"
    - "wlogout"
    - "gnome-calendar"
    - "gnome-weather"
    - "wlsunset"
    # - "grimblast-git"
